-- BORROWER360.SEMANTIC.BORROWER_360_MODEL: Cortex Analyst semantic view over BORROWER_360 + NBA_RECOMMENDATION.
-- Extracted via GET_DDL('SEMANTIC_VIEW','BORROWER360.SEMANTIC.BORROWER_360_MODEL') on 2026-08-29.

create or replace schema SEMANTIC COMMENT='Semantic views and Cortex Analyst / Agent surface.';

create or replace semantic view BORROWER_360_MODEL
	tables (
		BORROWER360.CURATED.BORROWER_360 primary key (BORROWER_ID),
		BORROWER360.AI.NBA_RECOMMENDATION comment='Next-best-action recommendations. status is ALWAYS PENDING_APPROVAL at creation. rule_basis is NOT NULL by construction.'
	)
	relationships (
		NBA_RECOMMENDATION_TO_BORROWER as NBA_RECOMMENDATION(BORROWER_ID) references BORROWER_360(BORROWER_ID)
	)
	facts (
		BORROWER_360.TOTAL_OUTSTANDING_INR as TOTAL_OUTSTANDING_INR,
		BORROWER_360.TOTAL_ARREARS_INR as TOTAL_ARREARS_INR,
		BORROWER_360.ARREARS_TO_CLEAR_FOR_UPGRADE_INR as ARREARS_TO_CLEAR_FOR_UPGRADE_INR,
		BORROWER_360.FOIR_TRUE_PCT as FOIR_TRUE_PCT,
		BORROWER_360.BT_RISK_SCORE as BT_RISK_SCORE,
		BORROWER_360.BT_RETENTION_VALUE_IF_OFFERED_INR as BT_RETENTION_VALUE_IF_OFFERED_INR,
		BORROWER_360.LTV_EXPECTED_INTEREST_INR as LTV_EXPECTED_INTEREST_INR,
		NBA_RECOMMENDATION.MARGIN_IMPACT_BPS as MARGIN_IMPACT_BPS
	)
	dimensions (
		BORROWER_360.BORROWER_ID as BORROWER_ID,
		BORROWER_360.FULL_NAME as FULL_NAME,
		BORROWER_360.CITY as CITY,
		BORROWER_360.STATE as STATE,
		BORROWER_360.CITY_TIER as CITY_TIER,
		BORROWER_360.OCCUPATION_TYPE as OCCUPATION_TYPE,
		BORROWER_360.MONTHLY_INCOME_INR as MONTHLY_INCOME_INR,
		BORROWER_360.BUREAU_SCORE as BUREAU_SCORE,
		BORROWER_360.BUREAU_SCORE_BAND as BUREAU_SCORE_BAND,
		BORROWER_360.OWN_LOAN_COUNT as OWN_LOAN_COUNT,
		BORROWER_360.OWN_PRODUCT_COUNT as OWN_PRODUCT_COUNT,
		BORROWER_360.BORROWER_ASSET_CLASS as BORROWER_ASSET_CLASS,
		BORROWER_360.IS_NPA as IS_NPA,
		BORROWER_360.NPA_UPGRADE_ELIGIBLE as NPA_UPGRADE_ELIGIBLE,
		BORROWER_360.PERFORMING_LOANS_DRAGGED_TO_NPA as PERFORMING_LOANS_DRAGGED_TO_NPA,
		BORROWER_360.IS_LOAN_STACKED as IS_LOAN_STACKED,
		BORROWER_360.TOTAL_LENDER_COUNT as TOTAL_LENDER_COUNT,
		BORROWER_360.EARLY_WARNING_MANDATES as EARLY_WARNING_MANDATES,
		BORROWER_360.BT_IS_A_FLIGHT_RISK as BT_IS_A_FLIGHT_RISK,
		BORROWER_360.N_INTERACTIONS as N_INTERACTIONS,
		BORROWER_360.OVERALL_SENTIMENT_DIRECTION as OVERALL_SENTIMENT_DIRECTION,
		BORROWER_360.ANY_PTP_MADE_THEN_MISSED as ANY_PTP_MADE_THEN_MISSED,
		BORROWER_360.ANY_REASON_CHANGE as ANY_REASON_CHANGE,
		BORROWER_360.DAYS_GAP_TREND as DAYS_GAP_TREND,
		BORROWER_360.N_PENDING_RECOMMENDATIONS as N_PENDING_RECOMMENDATIONS,
		BORROWER_360.HAS_COLLECTIONS_ACTION as HAS_COLLECTIONS_ACTION,
		BORROWER_360.HAS_RETENTION_OFFER as HAS_RETENTION_OFFER,
		BORROWER_360.HAS_GROWTH_OFFER as HAS_GROWTH_OFFER,
		BORROWER_360.IS_DEMO_CASE as IS_DEMO_CASE,
		BORROWER_360.DEMO_CASE_LABEL as DEMO_CASE_LABEL,
		NBA_RECOMMENDATION.RECOMMENDATION_ID as RECOMMENDATION_ID,
		NBA_RECOMMENDATION.BORROWER_ID as BORROWER_ID,
		NBA_RECOMMENDATION.LOAN_ID as LOAN_ID,
		NBA_RECOMMENDATION.ACTION_CODE as ACTION_CODE,
		NBA_RECOMMENDATION.ACTION_FAMILY as ACTION_FAMILY,
		NBA_RECOMMENDATION.RULE_BASIS as RULE_BASIS,
		NBA_RECOMMENDATION.MODEL_CONTRIBUTION as MODEL_CONTRIBUTION,
		NBA_RECOMMENDATION.BORROWER_FACING_MESSAGE as BORROWER_FACING_MESSAGE,
		NBA_RECOMMENDATION.EXPECTED_VALUE_INR as EXPECTED_VALUE_INR,
		NBA_RECOMMENDATION.BUREAU_DISCLOSURE as BUREAU_DISCLOSURE,
		NBA_RECOMMENDATION.REQUIRES_HUMAN_APPROVAL as REQUIRES_HUMAN_APPROVAL,
		NBA_RECOMMENDATION.STATUS as STATUS,
		NBA_RECOMMENDATION.CREATED_AT as CREATED_AT
	)
	comment='Unified borrower 360 for an Indian mixed-NBFC retail lending portfolio. Combines RBI-compliant credit risk classification (borrower-level, per IRAC norms), balance-transfer flight risk (structurally separated from credit risk - a distressed borrower always scores zero BT risk), a lifetime-value proxy (expected future interest income from the real amortization schedule, assuming the loan runs to full term), and sentiment/behavioral trajectory signals derived from sequenced call transcripts. Paired with the deterministic next-best-action recommendation engine, where every action traces to a named rule and carries an expected value.'
	ai_verified_queries (
		"0;1" AS (
QUESTION 'How many borrowers are in each RBI asset classification?'
VERIFIED_AT 1787330172
VERIFIED_BY 'Semantic Model Generator'
ONBOARDING_QUESTION false
SQL 'SELECT BORROWER_ASSET_CLASS, COUNT(*) FROM borrower_360 GROUP BY BORROWER_ASSET_CLASS'),
		"1;1" AS (
QUESTION 'Which borrowers are at highest risk of balance transfer, ranked by their lifetime value?'
VERIFIED_AT 1787330172
VERIFIED_BY 'Semantic Model Generator'
ONBOARDING_QUESTION false
SQL 'SELECT BORROWER_ID, FULL_NAME, LTV_EXPECTED_INTEREST_INR FROM borrower_360 WHERE BT_IS_A_FLIGHT_RISK = TRUE ORDER BY LTV_EXPECTED_INTEREST_INR DESC LIMIT 20'),
		"2;1" AS (
QUESTION 'Which borrowers have a deteriorating sentiment trajectory across their calls?'
VERIFIED_AT 1787330172
VERIFIED_BY 'Semantic Model Generator'
ONBOARDING_QUESTION false
SQL 'SELECT BORROWER_ID, FULL_NAME, OVERALL_SENTIMENT_DIRECTION, ANY_PTP_MADE_THEN_MISSED FROM borrower_360 WHERE OVERALL_SENTIMENT_DIRECTION = ''DETERIORATING'''),
		"3;1" AS (
QUESTION 'What pending collections actions are recommended and why?'
VERIFIED_AT 1787330172
VERIFIED_BY 'Semantic Model Generator'
ONBOARDING_QUESTION false
SQL 'SELECT r.BORROWER_ID, r.ACTION_CODE, r.RULE_BASIS, r.EXPECTED_VALUE_INR FROM nba_recommendation AS r WHERE r.STATUS = ''PENDING_APPROVAL'' AND r.ACTION_FAMILY = ''COLLECTIONS'''),
		"4;1" AS (
QUESTION 'How many NPA borrowers are eligible to upgrade back to standard?'
VERIFIED_AT 1787330172
VERIFIED_BY 'Semantic Model Generator'
ONBOARDING_QUESTION false
SQL 'SELECT COUNT(*) FROM borrower_360 WHERE IS_NPA = TRUE AND NPA_UPGRADE_ELIGIBLE = TRUE')
	);

-- BORROWER_360_AGENT: Cortex Agent, defined and version-controlled via
-- cortex_project/BORROWER_360_AGENT.agent.yaml (deploy with `snow agent deploy` / cortex_project
-- tooling rather than raw SQL). Captured here for reference - re-create with CREATE AGENT using
-- the agent_spec below if deploying by hand:
--
-- Tools: BorrowerAnalyst (cortex_analyst_text_to_sql over this semantic view) +
--        DecideRecommendation (generic tool wrapping BORROWER360.AI.SP_DECIDE_RECOMMENDATION) +
--        MCP server BORROWER360.APP.MCP_TEAM_TASKS (CreateTeamTasks).
-- Full agent_spec JSON is in agents/borrower_360_agent.yaml / proto/borrower_360_agent.yaml
-- in this repo.
